# Site
name: "eat with mee"
title: "eatwithmee"
description: "ryan chen eats food. follow me on instagram at @stumpyeatsfood"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'

google_analytics: 'UA-46278016-1'
disqus: 'eatwithmee'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ryan:
    name: Ryan
    display_name: Ryan
    gravatar: eb2b2ffd9b6bd2d1d5ea1e5311d94bb1
    email: ryanjchen2@gmail.com
    web: https://ryanjchen.com
    twitter: https://twitter.com/ryanjengchen
    description: "A hungry boi."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
